apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: atomic-dingo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: atomic-dingo-python 
  name: atomic-dingo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: atomic-dingo-python 
